### PR TITLE
update logos & minor update

### PR DESCRIPTION
**Pull request by Borda**
Changing logo to the @williamFalcon version and removing links on the bottom of the page

### CODE REVIEW

**Comment by Borda** [comment]
@luiscape do you know how to make the bottom black footer tinner?

**Comment by luiscape** [comment]
@Borda can you add a screenshot to explain what a thinner footer means?

**Comment by Borda** [comment]
I think it is not important now... :)
Screenshot at 2020-01-23 16-29-06

**Comment by mozharovsky** [comment]
Hey @Borda! 

The website looks good, although the footer still might be thinner, as you've mentioned. I've played around with different footer sizes to find the best-looking one.

That is how the footer looks right now:
pl_original

That is a slightly thinner footer version:
pl_footer_thin

That is a much thinner footer version:
pl_footer_super_thin

That is a no-footer version:
pl_footer_empty

Which one do you like most?

**Pull request merged**
