### PR TITLE
Improves Logic for Finding Theme Files

### PR DESCRIPTION
**Pull request by luiscape**
When trying to build the theme locally, I noticed that many files were not included in the original package. That was the case because the wild cards used in `setup.py` did not include sub-directories in the `static` path. That resulted in fonts and vendor JavaScript not being included in the final build, breaking the theme.

I solved that by adding a new recursive function that adds all paths from a given base path. In this case, it will distribute the theme package with all the files under the `static` directory.

cc @Borda 

--- 

👋 @Borda, on another note, it seems to me that this theme is still in alpha, right? I am asking because the theme is full of references to Facebook and the PyTorch project.

### CODE REVIEW

**Comment by Borda** [comment]
@williamFalcon could you enable/install the CircleCI checks... it dropped after moving to org too

**Comment by Borda** [comment]
@luiscape we have enabled the CI hook, could you please "update" PR to trigger refresh? The simplest way is rebase master...

**Comment by luiscape** [comment]
@Borda I merged `master` back into my fork but it didn't trigger Cricle. Would you like me to close and open the PR again?

**Comment by Borda** [comment]
Pls try rebase it on master... I ll check it later...

**Comment by luiscape** [comment]
I've already merged `master` into this branch, I don't see a need to do a rebase.

**Comment by luiscape** [comment]
I can close this PR and make a new one if that's easier. My changes were really small. :)

**Comment by williamFalcon** [comment]
probably easier to paste the changes onto a fresh copy from master

**Comment by Borda** [comment]
@luiscape even a small contribution can have a big value... I will test it locally and let you know, stay tuned... =)

**Comment by luiscape** [comment]
@williamFalcon Yeah, not a problem. 

@Borda let me close this one and create a fresh PR with my changes. (It'll take a few hours; I'm busy with other things.) That should trigger the right Circle checks. :) Before I do that, however, could you add me as a collaborator to this repo? That would avoid having me create a fork. (A collaborator _without_ rights to merge to master would work.) Let me know if that's possible.

**Comment by luiscape** [comment]
I have created a new clean PR here: https://github.com/PyTorchLightning/lightning_sphinx_theme/pull/3

**Pull request closed without merging**
